const tabs = document.querySelectorAll('.project-tabs button'); const track = document.querySelector('.project-track'); const allItems = Array.from(document.querySelectorAll('.project-item')); const dotsContainer = document.querySelector('.dots'); let currentIndex = 0; let visibleItems = []; let slideCount = 0; let itemsPerSlide = 3; function getItemsPerSlide() { const width = window.innerWidth; if (width < 768) return 1; else if (width < 1024) return 2; else return 3 }
function updateSlider() {
    itemsPerSlide = getItemsPerSlide(); visibleItems = allItems.filter(item => item.style.display !== 'none'); slideCount = Math.ceil(visibleItems.length / itemsPerSlide); dotsContainer.innerHTML = ''; for (let i = 0; i < slideCount; i++) { const dot = document.createElement('span'); dot.classList.add('dot'); if (i === Math.floor(currentIndex / itemsPerSlide)) dot.classList.add('active'); dot.addEventListener('click', () => goToSlide(i * itemsPerSlide)); dotsContainer.appendChild(dot) }
    visibleItems.forEach(item => item.classList.remove('active')); if (visibleItems[currentIndex]) visibleItems[currentIndex].classList.add('active'); const itemWidth = visibleItems[0]?.offsetWidth || 0; const gap = 30; const offset = -(currentIndex * (itemWidth + gap)); track.style.transform = `translateX(${offset}px)`
}
function goToSlide(index) { currentIndex = index; updateSlider() }
tabs.forEach(tab => { tab.addEventListener('click', () => { tabs.forEach(t => t.classList.remove('active')); tab.classList.add('active'); const filter = tab.getAttribute('data-filter'); allItems.forEach(item => { item.style.display = filter === 'all' || item.dataset.type === filter ? 'block' : 'none' }); currentIndex = 0; updateSlider() }) }); window.addEventListener('resize', () => { updateSlider() }); updateSlider(); document.addEventListener("DOMContentLoaded", function () {
    const testimonialTrack = document.querySelector('.testimonial-track'); const testimonialItems = document.querySelectorAll('.testimonial-item'); const testimonialPrev = document.getElementById('testimonialPrev'); const testimonialNext = document.getElementById('testimonialNext'); let testimonialIndex = 0; function updateTestimonialSlider() { const itemsPerSlide = window.innerWidth > 768 ? 2 : 1; const itemWidth = testimonialItems[0].getBoundingClientRect().width + 20; const translateX = testimonialIndex * itemWidth; testimonialTrack.style.transform = `translateX(-${translateX}px)` }
    testimonialNext.addEventListener('click', () => { const itemsPerSlide = window.innerWidth > 768 ? 2 : 1; const totalSlides = Math.ceil(testimonialItems.length / itemsPerSlide); testimonialIndex = (testimonialIndex + 1) % totalSlides; updateTestimonialSlider() }); testimonialPrev.addEventListener('click', () => { const itemsPerSlide = window.innerWidth > 768 ? 2 : 1; const totalSlides = Math.ceil(testimonialItems.length / itemsPerSlide); testimonialIndex = (testimonialIndex - 1 + totalSlides) % totalSlides; updateTestimonialSlider() }); window.addEventListener('resize', () => { testimonialIndex = 0; updateTestimonialSlider() }); updateTestimonialSlider()
}); document.addEventListener("DOMContentLoaded", function () {
    const starsContainers = document.querySelectorAll('.stars'); starsContainers.forEach(container => {
        const rating = parseFloat(container.getAttribute('data-rating')); const fullStars = Math.floor(rating); const halfStar = rating % 1 !== 0; let starsHTML = ''; for (let i = 0; i < fullStars; i++) { starsHTML += '<i class="fa-solid fa-star"></i>' }
        if (halfStar) { starsHTML += '<i class="fa-solid fa-star-half-stroke"></i>' }
        const emptyStars = 5 - Math.ceil(rating); for (let i = 0; i < emptyStars; i++) { starsHTML += '<i class="fa-regular fa-star"></i>' }
        container.innerHTML = starsHTML
    })
})